{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rakuten.zack.poc.simplesdk",
    "module": "util",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "util-0.1.0.aar",
          "url": "util-0.1.0.aar",
          "size": 2863,
          "sha512": "52c85469ee33d7db3fddd7fcc12a05e02f710b0b57b016dd5f3a2aae7ac46400380d20fa14a3ecd87476341282c9ae3a9cdbe2ddb068e8df9a118ca6b9d61736",
          "sha256": "d12bb88297af7272fe8fd65f2680082a4107fef889a316c85a8b3f9ba57cdf7d",
          "sha1": "3b5b5542211fae17f114bb37f1fd653d066d15ac",
          "md5": "65f6e5e8bab4c98df6ba0d5a934f47de"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.rakuten.zack.poc.simplesdk",
          "module": "core",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "util-0.1.0.aar",
          "url": "util-0.1.0.aar",
          "size": 2863,
          "sha512": "52c85469ee33d7db3fddd7fcc12a05e02f710b0b57b016dd5f3a2aae7ac46400380d20fa14a3ecd87476341282c9ae3a9cdbe2ddb068e8df9a118ca6b9d61736",
          "sha256": "d12bb88297af7272fe8fd65f2680082a4107fef889a316c85a8b3f9ba57cdf7d",
          "sha1": "3b5b5542211fae17f114bb37f1fd653d066d15ac",
          "md5": "65f6e5e8bab4c98df6ba0d5a934f47de"
        }
      ]
    }
  ]
}
