{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rakuten.zack.poc.simplesdk",
    "module": "widget",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "widget-0.0.1.aar",
          "url": "widget-0.0.1.aar",
          "size": 13996,
          "sha512": "55e3b7c9a4be4b0abeec9f66db3b9a2cf0f8e2f8b3b6be5611345d06d2b155a793893fdd7bdf1ba6232411a14fe756d9a46ccb1833a8ec32d2f319a98870adf4",
          "sha256": "a2b57f00caaa846be4f59d0f7db7bdc9fa7bf6bfff0b6f180cd7b2492d20316f",
          "sha1": "0f119a22ffe90cfc36253da07b4790da1f4d8fb3",
          "md5": "8af5fc1b3c40090aefeb03924f06f83a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "widget-0.0.1.aar",
          "url": "widget-0.0.1.aar",
          "size": 13996,
          "sha512": "55e3b7c9a4be4b0abeec9f66db3b9a2cf0f8e2f8b3b6be5611345d06d2b155a793893fdd7bdf1ba6232411a14fe756d9a46ccb1833a8ec32d2f319a98870adf4",
          "sha256": "a2b57f00caaa846be4f59d0f7db7bdc9fa7bf6bfff0b6f180cd7b2492d20316f",
          "sha1": "0f119a22ffe90cfc36253da07b4790da1f4d8fb3",
          "md5": "8af5fc1b3c40090aefeb03924f06f83a"
        }
      ]
    }
  ]
}
