{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rakuten.zack.poc.simplesdk",
    "module": "core",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.1.4.aar",
          "url": "core-0.1.4.aar",
          "size": 4954,
          "sha512": "23d127df5ac630d230a60987f13d573437d964937a0d1d6a897303dc6394fcbe4db633519c4f24a67d641847e656230e1209e1f228e42bf3818367fb2f046a9a",
          "sha256": "c2d3f4ff832cc6dcfc0c8515601479f8e57abf0600aa43639de1ca8d1a46bb2a",
          "sha1": "621fd2803730c6712259ffc386687f546ae9c9d4",
          "md5": "a7d0976fcc4824c81e09014c55a37121"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.1.4.aar",
          "url": "core-0.1.4.aar",
          "size": 4954,
          "sha512": "23d127df5ac630d230a60987f13d573437d964937a0d1d6a897303dc6394fcbe4db633519c4f24a67d641847e656230e1209e1f228e42bf3818367fb2f046a9a",
          "sha256": "c2d3f4ff832cc6dcfc0c8515601479f8e57abf0600aa43639de1ca8d1a46bb2a",
          "sha1": "621fd2803730c6712259ffc386687f546ae9c9d4",
          "md5": "a7d0976fcc4824c81e09014c55a37121"
        }
      ]
    }
  ]
}
