{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rakuten.zack.poc.simplesdk",
    "module": "core",
    "version": "0.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.1.6.aar",
          "url": "core-0.1.6.aar",
          "size": 4974,
          "sha512": "149e492f7acd393b4c84b82e4417dd761dc0765178adb7586cb569a9bab418ba395deb819de347228e08c823f0048d6aa75517f9fec428a2f0e9437779854dd2",
          "sha256": "f680273ae430c165270e3d420081bf69c5ae2f5272da8e3a893bbebf39388fc1",
          "sha1": "373dd560bd86a8b958e6cd41d129c47aa9794910",
          "md5": "089322e7b64297537289e53141be6d35"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.1.6.aar",
          "url": "core-0.1.6.aar",
          "size": 4974,
          "sha512": "149e492f7acd393b4c84b82e4417dd761dc0765178adb7586cb569a9bab418ba395deb819de347228e08c823f0048d6aa75517f9fec428a2f0e9437779854dd2",
          "sha256": "f680273ae430c165270e3d420081bf69c5ae2f5272da8e3a893bbebf39388fc1",
          "sha1": "373dd560bd86a8b958e6cd41d129c47aa9794910",
          "md5": "089322e7b64297537289e53141be6d35"
        }
      ]
    }
  ]
}
